sudo: false
language: python
cache: pip
python:
  - '3.6'

before_script:
  - pip install -q flake8 pytest pytest-cov codecov

script:
  - flake8 fflag/
  - python setup.py -q install
  - pytest --cov fflag/ tests/ --longrun

after_success:
  - codecov
